version: '3'
services:
  pgdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    image: node-app
    ports:
      - "3333:3333"
    depends_on:
      - pgdb
    environment:
      SEQ_DB: pursume
      SEQ_USER: postgres
      SEQ_PW: postgres
      PORT: 5432
      DATABASE_URL: postgres://postgres:postgres@pgdb:5432/pursume
